<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Mehul-SurfacePro7" name="com.qa.android.test.AppiumTest" tests="6" failures="1" timestamp="5 Sep 2021 11:37:02 GMT" time="76.857" errors="0">
  <testcase name="verifyRegisterFunctionality" time="31.032" classname="com.qa.android.test.AppiumTest"/>
  <testcase name="verifyTitle" time="0.388" classname="com.qa.android.test.AppiumTest"/>
  <testcase name="verifyShowProgressBarFunctionality" time="24.387" classname="com.qa.android.test.AppiumTest"/>
  <testcase name="verifyEnCTAFunctionality" time="1.998" classname="com.qa.android.test.AppiumTest"/>
  <testcase name="verifyChromeLogoCTAFunctionality" time="12.515" classname="com.qa.android.test.AppiumTest"/>
  <testcase name="unhandelledExceptionFail" time="6.537" classname="com.qa.android.test.AppiumTest">
    <failure type="java.lang.AssertionError" message="Homepage not available expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Homepage not available expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.qa.android.test.AppiumTest.unhandelledExceptionFail(AppiumTest.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- unhandelledExceptionFail -->
</testsuite> <!-- com.qa.android.test.AppiumTest -->
